# Generated by Django 4.2.7 on 2023-11-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
    ]
