# Generated by Django 4.2.7 on 2023-11-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.BooleanField(default=False, verbose_name='finalizado'),
        ),
    ]
